const nodemailer = require('nodemailer');
const fs = require('fs');
const path = require('path');
require('dotenv').config();

class EmailUtils {
    constructor() {
        this.transporter = nodemailer.createTransport({
            host: process.env.SMTP_HOST,
            port: parseInt(process.env.SMTP_PORT),
            secure: process.env.SMTP_SECURE === 'true',
            auth: {
                user: process.env.SMTP_USER,
                pass: process.env.SMTP_PASS
            }
        });
    }

    /**
     * Senders a high-fidelity evidence report for a failed automation run.
     */
    async sendFailureReport(brand, viewport, error, screenshotPath = null, videoPath = null) {
        // Dynamic recipient refresh
        const recipients = process.env.REPORT_EMAIL_RECIPIENT || 'deepali.londhe@magnetoitsolutions.com';
        console.log(`📧 [Email-Agent] Preparing failure report for ${brand} [${viewport}]...`);

        const attachments = [];
        if (screenshotPath && fs.existsSync(screenshotPath)) {
            attachments.push({ filename: `failure_screenshot.png`, path: screenshotPath });
        }
        if (videoPath && fs.existsSync(videoPath)) {
            attachments.push({ filename: `failure_video.webm`, path: videoPath });
        }

        const mailOptions = {
            from: `"FLM Automation Alert" <${process.env.SMTP_USER}>`,
            to: recipients,
            subject: `🚨 FAILURE ALERT: ${brand} [${viewport.toUpperCase()}]`,
            html: `
                <div style="font-family: Arial, sans-serif; border: 1px solid #ff4d4d; padding: 20px; border-radius: 10px; background-color: #fffafa;">
                    <h2 style="color: #d9534f;">⚠️ Automation Failure Detected</h2>
                    <p><strong>Campaign:</strong> ${brand}</p>
                    <p><strong>Environment:</strong> ${viewport}</p>
                    <p><strong>Error Detail:</strong> <span style="color: #d9534f; font-family: monospace;">${error}</span></p>
                    <hr/>
                    <p>The FLM Agent attempted to heal the process but encountered a critical obstacle. Attached is the visual evidence (Screenshot & Video) for your review.</p>
                    <p style="font-size: 12px; color: #777;">This is an automated report generated by the FLM Automation Suite.</p>
                </div>
            `,
            attachments: attachments
        };

        try {
            await this.transporter.sendMail(mailOptions);
            console.log(`✅ [Email-Agent] Evidence report sent successfully to: ${this.recipients}`);
        } catch (err) {
            console.error('❌ [Email-Agent] Failed to send email:', err.message);
        }
    }
}

module.exports = new EmailUtils();
